require "ifj21"

--deklarace
global franta : function(integer, string, number, number) : number, integer

--definice
function franta(a1:integer, a2:string, a3:number, a4:number) : number, integer
    local var1 : integer = 0
    local var2 : string = "ahoj"

end


function ivos(id:string): number
end

--franta()

--[[
require "ifj21"

function hlavni_program(year : integer)
  write("Hello from IFJ", year, "\n")
end

hlavni_program(21)
hlavni_program(22) -- pozdrav z budoucnosti
]]
